### PR TITLE
Take what is moved from atlas relationship-api

### PR DESCRIPTION
**Pull request by ruhan1**
Many classes and pom.xml are updated to make the transition smooth. And I changed the package name from "maven.atlas.graph*" to "cartographer.graph.*". I did "mvn clean install" and passed. I started standalone rest server, no problem. Please review.

### CODE REVIEW

**Comment by jdcasey** [comment]
retest this please

**Comment by ruhan1** [comment]
I just noticed running the carto IT need -Prun-its. I am going to look 
into the failed cases. I consider this a good opportunity to know more 
about code.

**Comment by jdcasey** [comment]
@ruhan1 sounds good. :smile:

**Comment by jdcasey** [comment]
retest this please

**Pull request merged**
